[tool.poetry]
name = "sendemail"
version = "0.1.0"
description = ""
authors = ["DavidEngle <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
yagmail = "^0.14.260"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
